services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    depends_on:
      - php-fpm
    environment:
      DOMAIN: ${DOMAIN:-localhost}
    labels:
      - traefik.enable=true
      - traefik.http.routers.caddy.rule=Host(`softavis.local`) || Host(`www.softavis.local`)
      - traefik.http.routers.caddy.entrypoints=https
      - traefik.http.routers.caddy.tls=true
#      - traefik.http.routers.caddy.tls.certresolver=dns-cloudflare
      - traefik.http.routers.caddy.tls.domains[0].main=softavis.local
      - traefik.http.routers.caddy.tls.domains[0].sans=*.softavis.local
    volumes:
      - .:/app
      - ./certs:/certs:ro
      - ./Caddyfile:/etc/caddy/Caddyfile
  php-fpm:
    image: php:8.3.9-fpm
    volumes:
      - .:/app
  traefik:
    image: traefik:v3.2.0
    depends_on:
      - caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`dashboard.softavis.local`)
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
#      - traefik.http.routers.traefik.tls.certresolver=dns-cloudflare
      - traefik.http.routers.traefik.tls.domains[0].main=softavis.local
      - traefik.http.routers.traefik.tls.domains[0].sans=*.softavis.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./traefik-dynamic.yaml:/etc/traefik/dynamic.yaml:ro
      - ./acme.json:/acme.json

networks:
  proxy:
    external: true