global:
  sendAnonymousUsage: false

api:
  debug: true
  dashboard: true

providers:
  docker:
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true

log:
  level: DEBUG
  format: common

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      tls:
        domains:
          - main: hristov.blog
            sans:
              - www.hristov.blog
    http3: {}

certificatesResolvers:
  dns-cloudflare:
    acme:
      email: about@z-latko.info
      storage: "/acme.json"
      dnsChallenge:
        provider: "cloudflare"
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"